### ISSUE TITLE
Put the long description in the PKG_INFO body?

### ISSUE THREAD

**Issue by lelit** [pdm-project/pdm-pep517#109]
Currently the sdist PKG_INFO produced by `pdm517` carries the whole _long description_ in the header `Description`.

Given that it support version 2.1 of the metadata format, wouldn't it be reasonable to use the [new way](https://peps.python.org/pep-0566/#description) of enclosing it? It would save some bytes (the `" " * 8` indent) if anything else, and looks better.

**Comment by frostming** [comment]
Closing as resolved
