### ISSUE TITLE
Missing setuptools in dev dependencies?

### ISSUE THREAD

**Issue by frenzymadness** [pdm-project/pdm-pep517#130]
It seems to me that setuptools should be listed in the list of dev dependencies in pyproject.toml because it's used by some fixtures in tests.

**Comment by frostming** [comment]
Can you point out what exact fixtures are depending on setuptools?

**Comment by frenzymadness** [comment]
I see these two files importing setuptools:
* tests/fixtures/projects/demo-cextension/build.py
* tests/fixtures/projects/demo-cextension-in-src/build.py

**Comment by frostming** [comment]
> I see these two files importing setuptools:
> 
> * tests/fixtures/projects/demo-cextension/build.py
> * tests/fixtures/projects/demo-cextension-in-src/build.py

Yes they are, would you like to contribute?
