### ISSUE TITLE
_bump_regex failure causes crash

### ISSUE THREAD

**Issue by DanLipsitt** [pdm-project/pdm-pep517#50]
Most PDM commands fail with an assertion failure if the most recent git tag ends in a letter, for example `v1.0.0b`.

Here is the source of the error:
https://github.com/pdm-project/pdm-pep517/blob/fa7ef3b7289badda3379fe537fb3436608552075/pdm/pep517/scm.py#L264-L266

I see that the example string is not [PEP440](https://www.python.org/dev/peps/pep-0440) compliant, but I don't think it's reasonable to expect that git tags in general would be. It might be reasonable to try to normalize the version string before bumping it, although the results might be unexpected. That would probably still be better than crashing, though. Alternatively, a better error message would be good.

I found a library called [parver](https://parver.readthedocs.io/en/latest/usage.html) that can do version normalization:
```python console
>>> parver.Version.parse('v1.1.1beta').normalize()
<Version '1.1.1b0'>
```

It still wouldn't handle arbitrary strings which means we still need some kind of fallback behavior, but it's an improvement:
```python console
>>> parver.Version.parse('beta').normalize()
ParseError: Expected v or int at position (1, 1) => '*beta'.
```

**Comment by frostming** [comment]
How do you reproduce the issue? pdm-pep517 uses packaging.version to normalize the string:

https://github.com/pdm-project/pdm-pep517/blob/fa7ef3b7289badda3379fe537fb3436608552075/pdm/pep517/scm.py#L245-L247

It is done in L246:

```python
>>> from pdm.pep517._vendor.packaging.version import parse
>>> str(parse('v1.0.0b'))
1.0.0b0
```

I see no crash happens even when I tag with `v1.0.0b`

**Comment by DanLipsitt** [comment]
Hmm, this was happening in one of my repos but now I can't reproduce it in a fresh one. I'll close this but keep an eye out in case it comes up again. Sorry for the incomplete report.
