### ISSUE TITLE
PEP 639 implementation

### ISSUE THREAD

**Issue by frostming** [pdm-project/pdm-pep517#76]
A new PEP has been accepted:

https://www.python.org/dev/peps/pep-0639/

**Comment by pawamoy** [comment]
That's great, I always add my name and a date to the license file, so had to specify license using a file, and the result was that pip and other tools would report the license as UNKNOWN. I was able to retrieve it from the classifiers, but that was less than optimal.
With this PEP we can both give the license file and the license SPDX name, great!

**Comment by pawamoy** [comment]
> If the license-files key is not present and not explicitly marked as dynamic, tools MUST assume a default value of the following:

    license-files.globs = ["LICEN[CS]E*", "COPYING*", "NOTICE*", "AUTHORS*"]

Nice, so my diffs will look like this:

```diff
 [project]
+license-expression = "ISC"
-license = {file = "LICENSE"}
 classifiers = [
     "Development Status :: 4 - Beta",
     "Intended Audience :: Developers",
-    "License :: OSI Approved :: ISC License (ISCL)",
 ]
```

Or if I want to be explicit:

```diff
 [project]
+license-expression = "ISC"
+license-files.paths = ["LICENSE"]
-license = {file = "LICENSE"}
 classifiers = [
     "Development Status :: 4 - Beta",
     "Intended Audience :: Developers",
-    "License :: OSI Approved :: ISC License (ISCL)",
 ]
```

Does PDM support this syntax? `license-files.paths = ...`

**Comment by frostming** [comment]
> Does PDM support this syntax? `license-files.paths = ...`

@pawamoy Of course, as long as it is a valid TOML syntax.
