### ISSUE TITLE
Suggestion: don't fallback to path backend for namespace packages when editables backend is selected

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm-pep517#79]
## Is your feature request related to a problem? Please describe.

The `src` layout has only one purpose: prevent running tests against the sources.
But it seems PDM, just like Poetry, adds my `src` directory to PYTHONPATH:

```console
$ python -c 'import sys; print("\n".join(sys.path))'
/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python38.zip
/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python3.8
/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python3.8/lib-dynload
/home/user/data/dev/project/__pypackages__/3.8/lib
/home/user/data/dev/project/src
/home/user/.local/lib/python3.8/site-packages
/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python3.8/site-packages

# disable PEP582
$ PYTHONPATH= python -c 'import sys; print("\n".join(sys.path))'
/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python38.zip
/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python3.8
/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python3.8/lib-dynload
/home/user/.local/lib/python3.8/site-packages
/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python3.8/site-packages
```

## Describe the solution you'd like

I would like PDM to avoid adding my `src` folder to PYTHONPATH. I want the installed version of my package to be used when I run my tests, or simply run an interpreter, not the source version. Adding the sources to PYTHONPATH hides potential packaging errors.

I can't seem to find where the `src` folder is added to PYTHONPATH, it does not seem to be in `sitecustomize.py` at least, so not sure if it's really PDM that adds it.

**Comment by frostming** [comment]
The problem is, `editables` backend isn't available for PEP 420 namespace packages. For such package, `path` backend is the only option.

**Comment by pawamoy** [comment]
In my case the hard failure would have let me know that I was missing an `__init__.py` module. It would have actually helped! Explicit is better than implicit 😄 ? If you deem it's better to silently fallback, it's fine, now I know not to make the same mistake. And maybe there are cases I didn't think about where falling back is helpful as well (multi-packages projects with namespace and non-namespace packages 🤔 ?)

**Comment by frostming** [comment]
It has nothing to do with correctness.`editables` just can't work for PEP 420 packages. PDM has no means to know whether you leave out the `__init__.py` intentionally or by mistake.

**Comment by pawamoy** [comment]
Of course, but if I *explicitely* select the `editables` backend and my package is a namespace package (voluntarily or not), I would like to at least see a warning that `editables` does not support it and that PDM falls back to the `path` backend instead. It is important to know it falls back because these backends have different consequences, namely the `path` backend will add the sources to PYTHONPATH.

**Comment by frostming** [comment]
A warning would be okay and easy to add.

**Comment by pawamoy** [comment]
Thank you so much!
